### ISSUE TITLE
315-5195: polarity of PIN_CS0 may be wrong

### ISSUE THREAD

**Issue by jotego** [furrtek/VGChips#12]
I think that the polarity, or maybe just the label polarity, for PIN_CSX signals is the other way around.

![imagen](https://user-images.githubusercontent.com/1863036/150999755-e54c4cc8-bbcc-408b-9672-eaa8b79d183f.png)

The way it is now, when the enable signal N18 is low, all PIN_CSX will be asserted. I think it makes sense for the labels to be the other way around: /PIN_CSX at the output of the NAND and PIN_CSX at the inverter output.

I also suggest to rename N18 to PIN_CS_EN

**Comment by furrtek** [comment]
N18 renamed to CS_EN, in order to keep the "PIN_" prefix for signals going to/coming from pins.
Thank you !
