### ISSUE TITLE
315-5195: A2 used as mapping

### ISSUE THREAD

**Issue by jotego** [furrtek/VGChips#7]
For banks 0,1, 4, 5, 6 and 7, **PIN_A2_IN** is used for generating the CS signal, whereas for banks 2 and 3, **PIN_A16_IN** is used. I don't think the system can work if A2 is used. Indeed, I have tried modifying the code so A2 is checked:

```
    for( aux=0; aux<8; aux=aux+1 ) begin
        case( mmr[ {1'b1, aux[2:0], 1'b0 } ][1:0] )
            0: active[aux] = { addr[23:17], aux==2 || aux==3 ? addr[16] : addr[2] } == mmr[ {1'b1, aux[2:0], 1'b1 } ];      //   64 kB
            1: active[aux] = addr[23:17] == mmr[ {1'b1, aux[2:0], 1'b1 } ][7:1]; //  128 kB
            2: active[aux] = addr[23:19] == mmr[ {1'b1, aux[2:0], 1'b1 } ][7:3]; //  512 kB
            3: active[aux] = addr[23:21] == mmr[ {1'b1, aux[2:0], 1'b1 } ][7:5]; // 2048 kB
        endcase
    end
```
You can see it in the case option 0. I tried several games but none booted. I think it must be PIN_A16_IN for all of them.

**Comment by furrtek** [comment]
Indeed ! It was a pinout mistake that wasn't corrected on all pages.
PIN_A2_IN is only connected to N27 in ADDRESS DECODING.
Schematics were updated.

**Comment by jotego** [comment]
Thank you!
